obj-$(CONFIG_MODEM_SHM_BUS) += shm_bus.o
obj-$(CONFIG_MODEM_SHM_BOOT) += shm_boot.o
obj-$(CONFIG_MODEM_SHM_DEV) += shm_dev.o
obj-$(CONFIG_MODEM_SHM_CHR) +=  shm_chr.o
obj-$(CONFIG_DUMMY_C2C) +=  dummy_c2c_genio.o
