
#ifndef __LINUX_VMACACHEDEFS_H
#define __LINUX_VMACACHEDEFS_H

#define VMACACHE_BITS 2
#define VMACACHE_SIZE (1U << VMACACHE_BITS)
#define VMACACHE_MASK (VMACACHE_SIZE - 1)

#endif /* __LINUX_VMACACHEDEFS_H */
