snd-soc-sa11x0-ssp-objs := sa11x0-ssp.o
obj-$(CONFIG_SND_SOC_SA11X0_SSP) += snd-soc-sa11x0-ssp.o

snd-soc-sa11x0-assabet-objs := sa11x0-assabet.o
obj-$(CONFIG_SND_SA11X0_ASSABET) += snd-soc-sa11x0-assabet.o
